### PR TITLE
Reproduce passage ranking and document ranking experiments

### PR DESCRIPTION
**Pull request by kevin-wangg**
- Reproduced pyserini passage ranking and document ranking experiments for the [screening exercise](https://github.com/lintool/guide/blob/master/ura.md)

Environment:
```bash
$ java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)

$ mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/homebrew/Cellar/maven/3.8.4/libexec
Java version: 11.0.9.1, vendor: Azul Systems, Inc., runtime: /Users/kevinwang/opt/anaconda3/envs/pyserini
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```
image

Issues encountered:
When running the unit tests, I get the following error
image
I'm still not entirely sure why this happens here are some of the things I've looked at:
- By default, the conda environment is set up with x86_64 architecture. However, it seems that Pytorch is still quite buggy on Rosetta as many tutorials on installing Pytorch on M1 Macs (eg [here](https://betterprogramming.pub/how-to-install-pytorch-on-apple-m1-series-512b3ad9bc6) and [here](https://min.news/en/tech/5e6bf957ff2b999266b5d56bc93a62b1.html)) specify ensuring it is running natively. However, when I set up the conda environment with arm_64 environment, not all python dependencies can be installed (eg. [onnxruntime ](https://github.com/microsoft/onnxruntime/issues/6633).
- I've also tried installing the nightly version of Pytorch, which also gave the same `illegal hardware instruction` error

However despite this error, I was still able to reproduce the experiment results.

### CODE REVIEW

**Comment by lintool** [comment]
I'm getting the error "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." when I navigate to https://github.com/castorini/pyserini/commit/8f90fe5172f4e18daa4d31329479890668b3fee8

Please change to the commit point of the source.

**Review by lintool — APPROVED** [review]

**Comment by lintool** [comment]
Sorry, I gave 🚢 it inadvertently. commit URL needs to be changed prior to merging.

**Comment by kevin-wangg** [comment]
Fixed commit URL.

**Comment by lintool** [comment]
@kevin-wangg can you resolve the conflicts please?

**Comment by kevin-wangg** [comment]
Resolved merge conflicts.

**Review by lintool — APPROVED** [review]

**Pull request merged**
