### PR TITLE
dsearch -> search.faiss

### PR DESCRIPTION
**Pull request by crystina-z**
For issue #1006 

Now I've move the folder `dsearch` into `search.faiss` and renamed `SimpleDenseSearcher` into `FaissSearcher`. 
all unittests has passed, still waiting for the pytest results.

lmk if I missed any files / conditions that need to be updated. also I hvn't added the fakes class and interface to make old API call works. wonder for which classes we'll wanna add this?

### CODE REVIEW

**Comment by lintool** [comment]
`integrations/dense/temp_cacm/cacm.json` shouldn't be part of the PR I think?

> also I hvn't added the fakes class and interface to make old API call works. wonder for which classes we'll wanna add this?

We should add facade classes to make the old `python -m pyserini.dsearch` driver work. Can you do that please? Like this:
https://github.com/castorini/pyserini/blob/master/pyserini/search/__main__.py

**Comment by crystina-z** [comment]
thanks! fixed the two above.
also wonder which classes should be included in the "dsearch/_deprecated.py" like this file - https://github.com/castorini/pyserini/blob/master/pyserini/search/_deprecated.py? e.g. do we need only the `xxSearcher` classes [here](https://github.com/castorini/pyserini/blob/master/pyserini/dsearch/__init__.py#L22-L23), or also the Encoders and other classes?

**Comment by lintool** [comment]
> thanks! fixed the two above. also wonder which classes should be included in the "dsearch/_deprecated.py" like this file - https://github.com/castorini/pyserini/blob/master/pyserini/search/_deprecated.py? e.g. do we need only the `xxSearcher` classes [here](https://github.com/castorini/pyserini/blob/master/pyserini/dsearch/__init__.py#L22-L23), or also the Encoders and other classes?

Yes, let's mirror @MXueguang 's PR as closely as possible - add stubs for the deprecated?

**Comment by crystina-z** [comment]
facade classes added and unittest passed

**Review by lintool — APPROVED** [review]

**Review by MXueguang — APPROVED** [review]
lgtm

**Pull request merged**
