### PR TITLE
Added Lucene tokenization to tests

### PR DESCRIPTION
**Pull request by lintool**
Captured results of Lucene tokenization so we can compare against XLM-R, mBERT, etc.

### CODE REVIEW

**Comment by keleog** [comment]
Lucene uses whitespace tokenization for all languages?

**Review by keleog — APPROVED** [review]

**Comment by lintool** [comment]
> Lucene uses whitespace tokenization for all languages?

We specify the name, e.g., `get_lucene_analyzer(name='french')`

**Comment by keleog** [comment]
> > Lucene uses whitespace tokenization for all languages?
> 
> We specify the name, e.g., `get_lucene_analyzer(name='french')`

yeah, but effectively just looks like language-specific stemming then white space tokenization for all.

**Comment by lintool** [comment]
I suppose? Implementation here: https://github.com/apache/lucene/tree/main/lucene/analysis/common/src/java/org/apache/lucene/analysis/fr

**Pull request merged**
