### PR TITLE
Refactor MIRACL/MrTydi 2CR into pyserini itself

### PR DESCRIPTION
**Pull request by jasper-xian**
Work in progress, working on #1438

Edit: commands as follows (identical for miracl and mrtydi)
```
# Run all languages for a specific condition and show commands
python -m pyserini.2cr.miracl --condition bm25 --directory runs --display-commands

# Run a particular language for a specific condition and show commands
python -m pyserini.2cr.miracl --condition bm25 --language ko --directory runs --display-commands

# Run all languages for all conditions and show commands
python -m pyserini.2cr.miracl --all --directory runs --display-commands

# For a specific condition, just show the commands and do not run
python -m pyserini.2cr.miracl --condition bm25 --display-commands --dry-run

# For a specific condition and language, just show the commands and do not run
python -m pyserini.2cr.miracl --condition bm25 --language ko --display-commands --dry-run

# For all conditions, just show the commands and do not run and skip evaluation
python -m pyserini.2cr.miracl --all --display-commands --dry-run --skip-eval

# Generate report
python -m pyserini.2cr.miracl --generate-report --output docs/2cr/miracl.html

# List conditions
python -m pyserini.2cr.miracl --list-conditions
```

### CODE REVIEW

**Comment by jasper-xian** [comment]
> When this is ready for review, can you drop in the commands I should run?

Yup, can do!

**Comment by jasper-xian** [comment]
I've left the commands in the PR description, am testing it myself now but feel free to check as well if you'd like

**Comment by lintool** [comment]
hi @jasper-xian can you follow the general design here? https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html

i.e., add `--list-conditions` and use `--condition` instead of `--encoder`.

**Comment by jasper-xian** [comment]
Ah sure, I can make that change

**Comment by jasper-xian** [comment]
> hi @jasper-xian can you follow the general design here? https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html
> 
> i.e., add `--list-conditions` and use `--condition` instead of `--encoder`.

Changes made as requested! Let me know if they look alright

**Comment by lintool** [comment]
```
% python -m pyserini.2cr.miracl --generate-report --output docs/2cr/miracl.html                 
% git diff
diff --git a/docs/2cr/miracl.html b/docs/2cr/miracl.html
index 69fe502..997e36d 100644
--- a/docs/2cr/miracl.html
+++ b/docs/2cr/miracl.html
@@ -1682,7 +1682,7 @@ Command to generate run:
 
   <blockquote class="mycode">
 <pre><code>python -m pyserini.fusion \
-  --runs  runs/run.miracl.bm25.ar.dev.top1000.txt runs/run.miracl.mdpr-tied-pft-msmarco.ar.dev.top1000.txt \
+  --runs  /run.miracl.bm25.ar.dev.top1000.txt /run.miracl.mdpr-tied-pft-msmarco.ar.dev.top1000.txt \
   --output run.miracl.bm25-mdpr-tied-pft-msmarco-hybrid.ar.dev.txt --method interpolation --alpha 0.5 --depth 1000 --k 1000
 </code></pre></blockquote>
...
```

I think your output is better, shouldn't append `runs/` directory, but shouldn't have leading slash either?

```bash
% python -m pyserini.2cr.miracl --generate-report --directory runs/ --output docs/2cr/miracl.html
% git diff
diff --git a/docs/2cr/miracl.html b/docs/2cr/miracl.html
index 69fe502..31cd532 100644
--- a/docs/2cr/miracl.html
+++ b/docs/2cr/miracl.html
@@ -261,14 +261,14 @@ Command to generate run:
   --language ar \
   --topics miracl-v1.0-ar-dev \
   --index miracl-v1.0-ar \
-  --output run.miracl.bm25.ar.dev.txt \
+  --output runs/run.miracl.bm25.ar.dev.txt \
   --batch 128 --threads 16 --bm25 --hits 1000
 </code></pre></blockquote>
 Evaluation commands:
 
   <blockquote class="mycode">
 <pre><code>python -m pyserini.eval.trec_eval \
-  -c -M 100 -m ndcg_cut.10 miracl-v1.0-ar-dev \
+  -c -M 100 -m ndcg_cut.10 miracl-v1.0-ar-dev runs/\
   run.miracl.bm25.ar.dev.txt</code></pre>
   </blockquote>
```

`--output` looks good, but the `trec_eval` command is wrong?

**Comment by lintool** [comment]
And what do command do I use if I want to run all conditions, all languages, everything everything?

**Comment by jasper-xian** [comment]
Ah hm, I'm not sure where that leading slash is from, I'll fix up the directory issues. And I can add a command to run everything everything as well

**Comment by jasper-xian** [comment]
I've made it possible to run all conditions by repurposing the `--all` flag, the edited run commands are in the PR description

**Comment by lintool** [comment]
Running this:

```bash
python -m pyserini.2cr.miracl --generate-report --output docs/2cr/miracl.html  
```

Why the change in score?

```bash
@@ -2000,7 +2000,7 @@ Evaluation commands:
 <td class="expand-button"></td>
 <td>mDPR (tied encoders), pre-FT w/ MS MARCO then in-lang FT w/ MIRACL</td>
 <td>0.725</td>
-<td>0.685</td>
+<td>0.684</td>
 <td>0.488</td>
 <td>0.565</td>
 <td>0.593</td>
```

**Comment by jasper-xian** [comment]
I noticed that as well, but it seems consistent with the current [miracl.yaml](https://github.com/castorini/pyserini/blob/9de33f7f8177800b1b7485104c5787af70fe2fa4/pyserini/resources/miracl.yaml#LL857C16-L857C16) file. I think it is due to making a fix to the score previously, but erroneously not updating the html file. I can update that with the current PR

**Comment by lintool** [comment]
> I noticed that as well, but it seems consistent with the current [miracl.yaml](https://github.com/castorini/pyserini/blob/9de33f7f8177800b1b7485104c5787af70fe2fa4/pyserini/resources/miracl.yaml#LL857C16-L857C16) file. I think it is due to making a fix to the score previously, but erroneously not updating the html file (commit [here](https://github.com/castorini/pyserini/commit/300cbb05024805fde34ff24514d337fb72b694a7)). I can update that with the current PR

okay, sg - as long as it's consistent with `miracl.yaml` I'm happy.

**Comment by lintool** [comment]
Next issue: I ran this:

```
python -m pyserini.2cr.miracl --all --directory=runs --display-commands
```

And got a bunch of these errors:

```
condition bm25-mdpr-tied-pft-msmarco-hybrid.ar:
  - split: train
Missing BM25 file: /run.miracl.bm25.ar.train.top1000.txt
  - split: dev
Missing BM25 file: /run.miracl.bm25.ar.dev.top1000.txt
...
```

The leading `/` suggests some type of path error?

**Comment by jasper-xian** [comment]
I've removed the leading `/` on my end, but it still seems to error with the `Missing BM25 file:`. When I run the script `run_all_miracl.py` this error occurs as well, perhaps because the path `f'runs/run.miracl.bm25.{lang}.{split}.top{hits}.txt'` doesn't pre-exist for me (I don't seem to have that file in the runs directory already)? The lines I'm referencing are [here](https://github.com/castorini/pyserini/blob/9de33f7f8177800b1b7485104c5787af70fe2fa4/scripts/repro_matrix/run_all_miracl.py#L83), L83-91. What was the intention of checking if the output file existed before running the command?

**Comment by lintool** [comment]
On my machine:

```
% ls runs | grep run.miracl.bm25.ar.train.top1000.txt
run.miracl.bm25.ar.train.top1000.txt
```

I believe a separate condition generates those runs... so it's likely an ordering issue? We just need to make sure the upstream run executes first?

**Review by lintool — APPROVED** [review]
lgtm!

**Pull request merged**
