### PR TITLE
TCT Colbert Dense retrieval reproduction

### PR DESCRIPTION
**Pull request by ArthurChen189**

### CODE REVIEW

**Comment by ArthurChen189** [comment]
Results:
#####################
MRR @10: 0.3349503115477319
QueriesRanked: 6980
#####################

Trec eval Results:
map                   	all	0.3416
recall_1000           	all	0.9640

Dense retrieval with TCT-ColBERT, HNSW index:
Hybrid Dense Sparse
#####################
MRR @10: 0.3529
QueriesRanked: 6980
#####################

Trec eval Results:
Results:
map                   	all	0.3594
recall_1000           	all	0.9698




MS MARCO Document Ranking
official metric MRR@100 using the official evaluation scripts:
#####################
MRR @100: 0.33231600332424854
QueriesRanked: 5193
#####################

Using `trec_eval` (MS-MARCO to TREC)
Results:
map                   	all	0.3323
recall_100            	all	0.8664


Dense-sparse hybrid retrieval (w/o document expansion)
#####################
MRR @100: 0.3701
QueriesRanked: 5193
#####################

To TREC
Results:
map                   	all	0.3701
recall_100            	all	0.9020

With document expansion
#####################
MRR @100: 0.3784402565752837
QueriesRanked: 5193
#####################


To TREC
Results:
map                   	all	0.3784
recall_100            	all	0.9081

**Comment by MXueguang** [comment]
which platform? Compute Canada right?
and we get exactly same numbers as the documents?

**Comment by ArthurChen189** [comment]
yes, on CC, the numbers exactly match the ones in the document

**Comment by MXueguang** [comment]
nice!

**Comment by ArthurChen189** [comment]
@MXueguang  thank you for your support on cc setup

**Comment by lintool** [comment]
@ArthurChen189 Nice! Can you write up the instructions for using CC, maybe put in `docs/usage-cc.md` or something like that? Send PR?

**Comment by ArthurChen189** [comment]
Yes, no problem. Also, I follow most instructions [here](https://github.com/castorini/onboarding/blob/master/docs/cc-guide.md). Should I start a new .md file or just update this one?

**Comment by lintool** [comment]
> @lintool Yes, no problem. Also, I follow most instructions [here](https://github.com/castorini/onboarding/blob/master/docs/cc-guide.md). Should I start a new .md file or just update this one?

Start a new .md file in this repo, but link to "common" instructions to the cc-guide - but supplement with any special instructions that are specific to dense retrieval, e.g., I recall space was an issue?

**Comment by ArthurChen189** [comment]
No problem, will do

**Comment by ArthurChen189** [comment]
@lintool Document created.

**Review by MXueguang — APPROVED** [review]
lgtm, thanks for the reproduction.
merging now, I'll do another pass on the cc-guide later

**Pull request merged**
