### PR TITLE
tokentest fix for issue

### PR DESCRIPTION
**Pull request by stephaniewhoo**
for issue https://github.com/castorini/pyserini/issues/469

but actually, it's weird I cannot reproduce those errors locally even in a refreshed repo. I am not sure if this is gonna fix for test_bert_dir error

### CODE REVIEW

**Comment by lintool** [comment]
Ah, I see the issue - I'm running `python -m unittest` from pyserini base directory... so relative paths are weird I think...

Look around, I think I had this issue in another test case, I had to code around it...

**Comment by lintool** [comment]
Still getting this error:

```
======================================================================
ERROR: test_bert_dir (tests.test_tokenize_json.TestTokenizeJson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/tests/test_tokenize_json.py", line 49, in test_bert_dir
    os.mkdir(indir)
FileExistsError: [Errno 17] File exists: './test_tokenize_json'
```

**Comment by stephaniewhoo** [comment]
sorry, pls try again. Should be ok now. It's because prev running has created dir and get aborted before cleanup.

**Review by lintool — APPROVED** [review]
confirmed fixed.

**Pull request merged**
