### PR TITLE
Add to onboarding reproduction logs

### PR DESCRIPTION
**Pull request by haeriamin**
Reproduced on Windows (WSL) with 12th Gen Intel(R) Core(TM) i7-12700F.

Environment:
Ubuntu 22.04.3 LTS
Python 3.10.12
Java 11.0.21
Apache Maven 3.6.3

Everything worked; Here are two example comparisons:

Screenshot 2024-02-28 002944

Screenshot 2024-02-28 000549

### CODE REVIEW

**Comment by lintool** [comment]
Hi @haeriamin do you mind resolving these conflicts, and we'll get your PR merged in? Thanks!

**Comment by haeriamin** [comment]
Hi @lintool sure, conflicts are resolved now.

**Comment by lintool** [comment]
Sorry, one more nit - can you move your entry down so they are sorted in chronological order?

**Comment by haeriamin** [comment]
Of course (I should have noticed that)!

**Review by lintool — APPROVED** [review]

**Pull request merged**
