### PR TITLE
DPR reproduction using dpr-nq-test index

### PR DESCRIPTION
**Pull request by ArthurChen189**
OS: Ubuntu 21.04
Top20	accuracy: 0.7800554016620499
Top100	accuracy: 0.8578947368421053

### CODE REVIEW

**Comment by lintool** [comment]
I can't figure out which condition you're trying to reproduce... is it "Natural Questions (NQ) with DPR-Multi"? Your reported figures don't seem to match any of the numbers in the page...

**Comment by ArthurChen189** [comment]
My apology for not clarifying. I tried wikipedia-dpr-multi-bf first but RAM OOM. @MXueguang recommended me to try the compressed version, which is [LINK](https://www.dropbox.com/s/t5mu2ii87rcnrmk/dindex-dpr-pq-2.tar.gz?dl=0).

**Comment by lintool** [comment]
What's the hardware config you're trying to run on? Is this CC?

**Comment by ArthurChen189** [comment]
This is not on CC. I am using my local machine which only has 16GB of RAM. Should I try this on CC?

**Comment by lintool** [comment]
I think so... @MXueguang have we been able to get this to run on CC? IIRC, we had storage issues?

**Comment by ArthurChen189** [comment]
I will try run this on CC again.

**Pull request closed without merging**
