### PR TITLE
Add colbert version of IBM reranker

### PR DESCRIPTION
**Pull request by yuki617**
We add a max-sim(colbert) operator option for ibm reranker.

### CODE REVIEW

**Comment by yuki617** [comment]
@stephaniewhoo The result I got on my laptop for alpha=0.3, max-sim operator =True running is here:
map:0.2236 ndcg:0.2908 mrr@10:0.2155.
Could you help on its replication? Thanks a lot!

**Comment by stephaniewhoo** [comment]
> @stephaniewhoo The result I got on my laptop for alpha=0.3, max-sim operator =True running is here:
> map:0.2236 ndcg:0.2908 mrr@10:0.2155.
> Could you help on its replication? Thanks a lot!

can you send me your new ibm model so that we can keep setup same

**Comment by yuki617** [comment]
> > @stephaniewhoo The result I got on my laptop for alpha=0.3, max-sim operator =True running is here:
> > map:0.2236 ndcg:0.2908 mrr@10:0.2155.
> > Could you help on its replication? Thanks a lot!
> 
> can you send me your new ibm model so that we can keep setup same

Please just use the last ibm model I sent you, the text_bert_tok_raw one is enough.

**Comment by stephaniewhoo** [comment]
> > > @stephaniewhoo The result I got on my laptop for alpha=0.3, max-sim operator =True running is here:
> > > map:0.2236 ndcg:0.2908 mrr@10:0.2155.
> > > Could you help on its replication? Thanks a lot!
> > 
> > 
> > can you send me your new ibm model so that we can keep setup same
> 
> Please just use the last ibm model I sent you, the text_bert_tok_raw one is enough.

can you try this setup except self_tran is 0.1? As I have this result under self_tran is 0.1
```cat ibm/result-ibm-0.1.json 
{"map": "0.2240", "ndcg": "0.2923"}```

**Comment by yuki617** [comment]
> > > > @stephaniewhoo The result I got on my laptop for alpha=0.3, max-sim operator =True running is here:
> > > > map:0.2236 ndcg:0.2908 mrr@10:0.2155.
> > > > Could you help on its replication? Thanks a lot!
> > > 
> > > 
> > > can you send me your new ibm model so that we can keep setup same
> > 
> > 
> > Please just use the last ibm model I sent you, the text_bert_tok_raw one is enough.
> 
> can you try this setup except self_tran is 0.1? As I have this result under self_tran is 0.1
> 
> ```
> {"map": "0.2240", "ndcg": "0.2923"}```
> ```
Yes, I got the same score as yours. I kept the selfTrans score to be 0.35 just for simplicity as our default ibm one is 0.35.

**Review by stephaniewhoo — APPROVED** [review]

**Pull request merged**
