### PR TITLE
add reproduction log pyserini version

### PR DESCRIPTION
**Pull request by MehrnazSadeghieh**
Dear Dr. Lin,

I just finished the third step of the onboarding path. First of all, I want to mention that my operating system is macOS version 12.7.5, and I have done all the processes on my terminal. For running the code part you wrote in the guide, I wrote that code in Sublime Text, and after saving, I ran it on the terminal too. In the Pyserini: BM25 Baseline for MS MARCO Passage Ranking guide, everything was fine, and I was able to run all the commands without any problems. As the process was similar to the Anserini one, I was able to finish and understand it sooner.

As you mentioned in the guide, the most difficult part was the installation process of Pyserini. In addition to the many challenges I faced with my network, I encountered another issue as well. I will discuss all my challenges and describe what I did to solve them. Initially, I wanted to avoid installing Anaconda and planned to download all the requirements separately. However, due to incompatibility between the libraries that i installed, I was unable to continue with this approach i did many tries but i was unable to fix nmslib’s incompability. Then I thought that you must have known something when you recommended installing Anaconda. Sorry that I did not follow your advice initially.

After installing Anaconda, the first steps of the installation process were fine, aside from my connection problems. For cloning the repository, my challenge was that I did not have an SSH key for my GitHub account and the way you asked us to clone needed one. Once I created one, the problem was solved. However, I had another issue with the clone command due to my poor and unstable internet connection. I received a message in the terminal saying it failed to clone tools directory. I removed my cloned repository and cloned it again four or five times, and finally, the problem was fixed.

Now, let's jump into my last issue, which I still do not understand why it happened. When I wanted to confirm everything is working by entering `python -m unittest`, I got many errors, including `ModuleNotFoundError: No module named 'faiss'`. I couldn't understand the problem because I verified that Faiss was installed with the command `python -c "import faiss; print(faiss.__version__)"`, and it looked fine. After a lot of searching, I gave up on my attempts. So, I decided to remove the whole conda environment and my cloned repository and follow all the steps again. Fortunately, this had a good result, and everything worked fine for me.

Thanks a lot for your comprehensive guide. I am really learning new things from them.

### CODE REVIEW

**Comment by MehrnazSadeghieh** [comment]
Dear Dr. Lin,

I just committed my changes for step 4 of the onboarding path. Everything worked fine with no issues.

Thanks a lot.

**Comment by lintool** [comment]
hi @MehrnazSadeghieh please continue and complete the onboarding exercises.

**Comment by MehrnazSadeghieh** [comment]
> hi @MehrnazSadeghieh please continue and complete the onboarding exercises.

hi Dr. Lin sure i will continue until i complete the entire onboarding path
Thanks again

**Comment by MehrnazSadeghieh** [comment]
> hi @MehrnazSadeghieh please continue and complete the onboarding exercises.

Dear Dr. Lin,

I just finished all the steps in the onboarding path.

All the steps worked fine, and thanks for your comprehensive documents.

I really want to continue my master's degree in this field, and reviewing most of the things that I learned in my university courses really helped me to organize my thoughts again in this area.

Thanks a lot for your time.

**Comment by lintool** [comment]
See: https://github.com/castorini/anserini/discussions/2428

**Comment by MehrnazSadeghieh** [comment]
> See: [castorini/anserini#2428](https://github.com/castorini/anserini/discussions/2428)

Hi Dr.Lin
Sorry for that
I think i solved the problem
Please let me know if any more changes are needed

**Pull request merged**
