### PR TITLE
Fix environment

### PR DESCRIPTION
**Pull request by MXueguang**
I fix faiss-cpu as 1.6.5 since 1.7.0 gives slightly different result. We can update to 1.7.0 in future release.

### CODE REVIEW

**Comment by lintool** [comment]
How different are the results?

`faiss-cpu` doesn't install at 1.6.5 and 1.7.0 on `orca`, getting [this error](https://github.com/facebookresearch/faiss/issues/1560).

This does work, however:

```
$ sudo pip install faiss-cpu==1.6.1
```

I'm running the experiments on `orca` right now.

**Comment by lintool** [comment]
@ronakice your call on this?

**Comment by ronakice** [comment]
@lintool both 1.6.5 and 1.7 work on `orca` with `virtualenv`?

**Comment by ronakice** [comment]
Also, sure we can stick with `1.6.5` for now.

**Review by ronakice — APPROVED** [review]
LGTM!

**Pull request merged**
