### PR TITLE
config pooling and l2norm for autoencoder

### PR DESCRIPTION
**Pull request by MXueguang**
https://github.com/castorini/pyserini/issues/1720

### CODE REVIEW

**Comment by MXueguang** [comment]
@lintool  do we want to make `prefix` configurable for `AutoEncoder` as well? E.g. e5 is prepending "query: " and "document: " to the text.

**Comment by lintool** [comment]
> @lintool do we want to make `prefix` configurable for `AutoEncoder` as well? E.g. e5 is prepending "query: " and "document: " to the text.
> 
> or it can be handled in raw data pre-processing.

I think yes?

@crystina-z @ronakice can you review?

**Comment by MXueguang** [comment]
okay updated, ready for review

**Comment by marcospiau** [comment]
Hi @MXueguang, I was looking into your PR because, coincidentally, I will also need to use e5 models as encoders. Is there any particular reason for hard coding these values for sentence-transformer models? `kwargs.update(dict(pooling='mean', l2_norm=True))` (here is the permalink: https://github.com/MXueguang/pyserini/blob/7d40eef1f9b3baf771c5e307265b8dba40719c84/pyserini/encode/__main__.py#L60C58-L60C58).

I noticed this because the embeddings when using `pyserini.encode` with `--prefix "passage:"` and `--encoder-class auto` were the same as if no prefix was used. Using `--encoder-class sentence-transformers` resulted in the expected values.

Also, a related question: Are there any conceptual differences between "auto" and "sentence-transformers" encoder classes?

**Comment by MXueguang** [comment]
Hi @marcospiau,
the hard code sentence-transformer setting was originally to reproduce https://github.com/castorini/pyserini/blob/master/docs/experiments-sbert.md

I just realise they all share the AutoDocumentEncoder, so should be same?

> I noticed this because the embeddings when using pyserini.encode with --prefix "passage:" and --encoder-class auto were the same as if no prefix was used. 

this issue was found in this PR?

**Comment by marcospiau** [comment]
@MXueguang Thanks, the hardcoded part now makes sense. Sorry, but by mistake I switched the `--encoder-class` part. Using `--encoder-class auto` and specifying a prefix works as expected; using `--encoder-class sentence-transformers`  and a prefix results in the same scores as not using a prefix.

Thanks!

**Review by lintool — APPROVED** [review]

**Pull request merged**
