### PR TITLE
MSMARCO doc/passage reproduction

### PR DESCRIPTION
**Pull request by nimasadri11**
## System Configuration and Environment:
* AWS EC2 t3a.2xlarge instance
* OS: Ubuntu
* 256 GB SSD
* 32GB RAM
* OpenJDK version: 11.0.11

## Issues encountered:
No issues encountered.

### CODE REVIEW

**Comment by MXueguang** [comment]
just to confirm.
the results you get are exactly same with the numbers in the documents?

**Comment by nimasadri11** [comment]
@MXueguang  Yes!

**Comment by lintool** [comment]
Hi @nimasadri11 - can you resolve these conflicts and then I'll merge?

**Comment by nimasadri11** [comment]
@lintool Resolving merge conflicts: done!

**Review by lintool — APPROVED** [review]

**Pull request merged**
