### PR TITLE
Updates to TCT-ColBERT dense retrieval replication

### PR DESCRIPTION
**Pull request by lintool**
Minor tweaks to get replication working on my Mac.

Primarily for @MXueguang to CR, but need @rodrigonogueira4 or @ronakice for +1 once @MXueguang is happy.

HNSW, efficiency:

```
trial 1: 6980/6980 [05:16<00:00, 22.08it/s]
trial 2: 6980/6980 [05:02<00:00, 23.04it/s]
```

What Xueguang got:

```
#####################
MRR @10: 0.33395142584254184
QueriesRanked: 6980
#####################
```

What I got:

```
#####################
MRR @10: 0.33394187474416553
QueriesRanked: 6980
#####################
```

Small differences in scores.

Brute force, efficiency:

```
trial 1: 582/582 [28:28<00:00,  2.93s/it]
trial 2: 582/582 [27:20<00:00,  2.82s/it]
```

What Xueguang got:

```
#####################
MRR @10: 0.3344603629417369
QueriesRanked: 6980
#####################
```

What I got:

```
#####################
MRR @10: 0.3343958930276968
QueriesRanked: 6980
#####################
```

Small differences in scores.

Not sure what's causing the issue.... perhaps related to https://github.com/castorini/pyserini/issues/257 ?

### CODE REVIEW

**Comment by MXueguang** [comment]
modifications LGTM.
not sure why there is small difference rn, will take a look. 
My intuition is it doesn't relate to  https://github.com/castorini/pyserini/issues/257 since we don't depend on anserini here?
Maybe some "random" thing in faiss search or some 'tie' cases ordered differently by multithreading

**Comment by lintool** [comment]
> My intuition is it doesn't relate to #257 since we don't depend on anserini here?
> Maybe some "random" thing in faiss search or some 'tie' cases ordered differently by multithreading

#257 is fundamentally about tie-breaking... which I suspect is the case here also... I'm not worried about this, but we should keep track moving forward.

**Review by MXueguang — APPROVED** [review]

**Comment by lintool** [comment]
For the record, my system:

Screen Shot 2021-01-04 at 9 17 49 PM

For the performance measurements above.

**Comment by justram** [comment]
HNSW index replication on our Ubuntu workstations:

Machine1 (Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz) 56 cores):
>  6980/6980 [11:52<00:00, 9.79it/s]
>  MRR@10: 0.33395142584254184

Machine2 (Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz  56 cores):
> 6980/6980 [07:21<00:00, 15.80it/s]
> MRR@10: 0.33395142584254184

**Comment by lintool** [comment]
@MXueguang what OS did you run your original experiments on?

**Comment by MXueguang** [comment]
My setting for origional experiments:
```
OS: Ubuntu 20.04.1 LTS
Processor Intel Core i7-8700k CPU @ 3.70GHz x 12
```

**Pull request merged**
