### PR TITLE
BEIR word piece tokenizer domain analysis

### PR DESCRIPTION
**Pull request by amyxie361**
1. tokenize_corpus.py and tokenize_queires.py are modified from pyserini.scripts.ltr_msmarco.convert_common.get_retokenized, which apply the bert-base-uncased tokenizer to the corpus.
2. compare_domains.py contains functions for compute the domain similarity, including jaccard and weighted jaccard of the vocabulary, also apply filters based on the term frequency or document frequency on the vocab.

### CODE REVIEW

**Comment by NThakur20** [comment]
Sorry, I did not get time today. 
I will have a look tomorrow morning at this pull request.

Kind Regards,
Nandan Thakur

**Review by NThakur20 — COMMENTED** [review]
Hi @amyxie361, 

Overall good work, thanks for all the metrics for evaluation. I think I found a mistake in the weighted Jaccard similarity code. From the BEIR paper snippet below, you can see that I have defined the normalized frequencies: S<sub>k</sub> and T<sub>k</sub> which is divided over the sum of all frequencies of all words in the dataset. 

However, in ``compare_domains.py``, you have missed normalizing the datasets, which might be why the weighted Jaccard similarity score is giving you bad scores for dataset imbalance between target and source. Adding a single line of dividing the ``cfs[d]`` with the sum of all tokens in the dataset might do the trick. 

Screenshot from 2022-05-11 07-40-52

Another suggestion would be to give the user to include different backbone model tokenizers such as RoBERTa and DistilBERT and check the domain analysis instead of BERT. DPR model is based on BERT, the ANCE model is based on RoBERTa and TAS-B model is based on DistilBERT. It will be interesting to check whether there is a correlation between for eg. the ANCE model vs. the TAS-B model on TREC-COVID due to its better tokenizer and better source-target overlap between MSMARCO and TREC-COVID?
 
I hope it helps! Apologies for the delay!
 
Kind Regards,
Nandan Thakur

**Comment by amyxie361** [comment]
Hi Nandan,
Thanks for taking time to look at this and giving useful suggestions! 
I've updated accordingly.

Best,
Yuqing

**Review by NThakur20 — APPROVED** [review]
Looks good to me! 

Kind Regards,
Nandan Thakur

**Pull request merged**
