### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lintool**
Example rewritten using f-strings.

### CODE REVIEW

**Comment by lintool** [comment]
Is that a safe assumption to make you think? What's the acceptance/adoption in industry in your experience?

**Comment by emmileaf** [comment]
> Is that a safe assumption to make you think? What's the acceptance/adoption in industry in your experience?

>=3.5 might be a safer assumption imo, although it probably isn't a big deal... I can't recall where else in the package has the >=3.6 dependency, but would probably feel less justified to enforce it if f-strings is the only version-dependent feature? If something else already requires the 3.6+ though, then that's a different story, of course.

**Comment by lintool** [comment]
@emmileaf I asked Twitter... let's see what people say: https://twitter.com/lintool/status/1229480636479660034

**Comment by lintool** [comment]
hey @emmileaf - @tuzhucheng makes a convincing case, I think:
https://twitter.com/tuzhucheng/status/1229529691519774720

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Given that Python 3.6 was first released in December 2016, I&#39;d say those using older releases should upgrade, given the pace of how fast things change now. It&#39;s also quite easy to create virtual environments with different Python 3.x versions.</p>&mdash; Michael Tu (@tuzhucheng) <a href="https://twitter.com/tuzhucheng/status/1229529691519774720?ref_src=twsrc%5Etfw">February 17, 2020</a></blockquote>

Thoughts?

**Comment by emmileaf** [comment]
Hmm that's a good point too, legacy users gotta upgrade sometime or another. Let’s roll forward with the f-strings then?

**Pull request merged**
