### PR TITLE
Update pooling options

### PR DESCRIPTION
**Pull request by jonhilgart22**
For some models, such as e5 ([see here ](https://huggingface.co/intfloat/e5-large-v2)), we need the option to specify mean pooling instead of just cls pooling.

### CODE REVIEW

**Comment by lintool** [comment]
@crystina-z or @MXueguang can either of you take a look at this?

**Comment by jonhilgart22** [comment]
@crystina-z or @MXueguang Let me know what you think. This is helpful for us running the `https://huggingface.co/intfloat/e5-large-v2` models

**Comment by MXueguang** [comment]
yes, this change looks good to me.

**Comment by MXueguang** [comment]
I think e5 also needs adding prefix "passage: ", easy to adding to this PR also?

**Comment by jonhilgart22** [comment]
> I think e5 also needs adding prefix "passage: ", easy to adding to this PR also?

I don't think we should tie this to `e5`; I was only giving that as an example. However, happy to add if you'd like!

**Comment by MXueguang** [comment]
yeah, lets deal with that in other PR if needed, current change should be good to merge

**Review by MXueguang — APPROVED** [review]

**Pull request merged**
