### PR TITLE
Adds reproduction logs for onboarding docs

### PR DESCRIPTION
**Pull request by UShivani3**
Environment:
Apple m1

While following `docs/installation.md` faced trouble with pip installation of `Pyserini`. 

Following are the steps I followed before encountering the error:

1. Environment creation and it's activation:
```
$ conda create -n pyserini python=3.8
$ conda activate pyserini
```

2. JDK 11 installation:
`$ conda install -c conda-forge openjdk=11
`

3. Pip installation for Pyserini:
`pip install pyserini`

Referring this GitHub [issue](https://github.com/nmslib/nmslib/issues/476) I was able to overcome the issue with `nmslib` (previously the build was getting stuck for both `lightgbm` and `nsmlib`). However, the one with `lightgbm` still persists.

Screenshot for the error:
Screenshot 2023-08-29 at 1 53 58 PM

### CODE REVIEW

**Comment by lintool** [comment]
ugh... configuring Python env sucks.

This is what I tried on my M1 Mac... give it a shot?

```
% conda env list
% conda create -n pyserini-dev python=3.8
% conda activate pyserini-dev

% conda install wget
% conda install -c conda-forge openjdk=11
% conda install -c conda-forge maven
% conda install -c conda-forge lightgbm
% conda install -c conda-forge faiss-cpu
% conda install pytorch torchvision torchaudio -c pytorch
% pip install --no-binary :all: nmslib
% pip install -e .
```

@yilinjz @sahel-sh you tried to get this working recently... any words of wisdom? Ref: #1599

**Comment by yilinjz** [comment]
Hi @UShivani3, I just repeated your steps on my M2 MacBook and the Pip installation worked for me (However I do recall seeing similar errors a few days ago when I installed pyserini for the first time ...). Below are a few things you could try:

1. Try the Development Installation as @lintool posted above.
2. Check your java/maven/pip versions (in conda env). Mine are java@11.0.13, mvn@3.9.4, pip@23.2.1
3. Check your conda version. Mine is 23.7.2 (also as a side note, did you install the ARM64 conda for M1/M2 or the x86 conda for Intel Mac plus Rosetta for translation?)

It's worth mentioning that, as discussed in #1599 , I encountered other issues in the later steps with M2 Mac, hence I would also suggest trying the installation on Intel Mac or on Linux if possible.

**Comment by UShivani3** [comment]
Hey @yilinjz, steps mentioned by @lintool worked for setting up the environment. Thanks for your help.
Now, I ran into errors mentioned in #1599.

**Comment by yilinjz** [comment]
@UShivani3 That is... both good and bad news; the good news is that it's then likely to be a system issue (rather than human mistakes), but the bad news is that you will need all unit tests to pass to be able to continue.

One thing I noticed was that when running **python -m unittest**, the following error messages were printed before the actual tests started:

[0.003s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016b124000-0x000000016b130000).
[0.003s][warning][os,thread] Attempt to deallocate stack guard pages failed.

I found discussions about this issue on StackOverflow (https://stackoverflow.com/questions/75899016/error-attempt-to-protect-stack-guard-pages-failed) but unfortunately there is no answer yet. This is related to JavaThread, and personally I strongly suspect this to relate to the issues in #1599 , but I don't have a solution yet either (and thus switched to ubuntu).

There are a few possibilities regarding why this issue may occur:
- The 23.7.2 Conda version caused this issue (possible but not very likely)
- The ARM64 Conda distribution caused this issue (this would be my guess)

**Comment by yilinjz** [comment]
Hi Professor @lintool , could you please share your Conda version with us? Thank you!

**Comment by lintool** [comment]
```
% conda info

     active environment : pyserini-dev
    active env location : /Users/jimmylin/opt/anaconda3/envs/pyserini-dev
            shell level : 2
       user config file : /Users/jimmylin/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/jimmylin/opt/anaconda3  (writable)
      conda av data dir : /Users/jimmylin/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jimmylin/opt/anaconda3/pkgs
                          /Users/jimmylin/.conda/pkgs
       envs directories : /Users/jimmylin/opt/anaconda3/envs
                          /Users/jimmylin/.conda/envs
               platform : osx-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Darwin/22.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

**Comment by yilinjz** [comment]
@UShivani3 So the issue is caused by Conda's 23.7.2 ARM64 distribution (not sure if the same issue existed in earlier versions), I've put detailed steps to fix this issue under #1599 .

**Comment by UShivani3** [comment]
Update on this PR.
Seems like issue was related to the Conda installation only. I followed the steps mentioned in #1599 for installing Intel distribution and everything worked fine. I was able to reproduce all of the results correctly.

Thanks @lintool and @yilinjz for your help.

**Comment by UShivani3** [comment]
Things that might be helpful if added in the documentation:

1. The Apple m1 chip and Conda installation related issue that I faced, maybe it's a good thing to include for troubleshooting.
2. Adding a note of cloning the repo on your account and moving ahead.
3. If possible we can just have some log files of the results can be saved on the drive for future reference.

**Comment by lintool** [comment]
@UShivani3 can you please resolve conflicts?

**Comment by UShivani3** [comment]
> @UShivani3 can you please resolve conflicts?

Done

**Review by lintool — APPROVED** [review]

**Pull request merged**
