### PR TITLE
Added acl lucene demo

### PR DESCRIPTION
**Pull request by billcui57**
### What was done

- Added a web server that demonstrates retrieval from the `ACL anthology` dataset
image

### How it was done

- Followed through steps to generate `ACL` index from [working-with-acl-anthology.md](https://github.com/billcui57/pyserini/blob/master/docs/working-with-acl-anthology.md)
- Copy pasted the generated index into `Pyserini` `/indexes` directory
- Created web server that points `Lucene` at that index

### Notes

- Only sparse search was used. I.e this demo is only backed by `LuceneSearcher`
- Multiple languages not supported

### CODE REVIEW

**Comment by lintool** [comment]
hey @ehsk @mobehbooei can you take a look and try it out?

**Comment by ehsk** [comment]
I followed the instructions and was able to run the demo.
The content column is shown as HTML, and it'd be great if it is rendered accordingly.

**Comment by billcui57** [comment]
> The content column is shown as HTML, and it'd be great if it is rendered accordingly. 
Could you please elaborate on this? What should the content column render instead? @ehsk

**Comment by ehsk** [comment]
The content of the returned documents is sometimes an HTML code. I was wondering if they can be rendered instead of being shown as raw text, but just realized that not all documents contain HTML code, so I think no need to do anything.

image

**Review by lintool — APPROVED** [review]

**Pull request merged**
