### PR TITLE
experiments-msmarco-passage: Done

### PR DESCRIPTION
**Pull request by shakibaam**
I successfully completed all the steps in this stage without any issues. In some steps, as I was using the Windows operating system, I had to adapt certain commands to be compatible with this operating system to ensure they executed correctly. Attached are some images of the completed steps.

### CODE REVIEW

**Comment by lintool** [comment]
Please continue along the onboarding path until you reach the end of the exercises, and then we'll take a look all at once.

**Comment by shakibaam** [comment]
I am currently working on the Pyserini Contriever Baseline for the NFCorpus phase. Although I have installed the Pyserini package on my E drive, I encountered an issue where my C drive ran out of space during the indexing process. How can I solve this issue?

**Comment by shakibaam** [comment]
I have completed all the onboarding path steps. The operating system on which I completed this task was Windows. All the commands and code executed without any issues, and only some of the commands were adjusted to be compatible with the Windows operating system to ensure proper execution.

**Comment by shakibaam** [comment]
I have now used the commit ID from the main trunk of both repositories, 'pyserini' and 'anserini,' and added it to the log.

**Review by lintool — APPROVED** [review]

**Pull request merged**
