### PR TITLE
Fix broken tests related to trec_eval computing unjudged

### PR DESCRIPTION
**Pull request by lintool**

### CODE REVIEW

**Review by rodrigonogueira4 — APPROVED** [review]

**Comment by rodrigonogueira4** [comment]
Hey @lintool, now that we removed the judged@10/20 from the output, `def test_undjudged_keep()` is not testing the judge calculation anymore, right?

**Comment by lintool** [comment]
yes, it's just a generic "baseline" test

**Comment by rodrigonogueira4** [comment]
But shouldn't we also test the judged calculations here?

**Comment by lintool** [comment]
Yea, I was going to circle around and look at it in detail later: noted as part of #1158

I was planning on doing some refactoring, to make consistent with other metrics, something like `-m judged.10,20`

**Comment by rodrigonogueira4** [comment]
Ok!

**Pull request merged**
