### PR TITLE
Add Onboarding Logs

### PR DESCRIPTION
**Pull request by AhmedEssam19**
Software: Ubuntu 22.04, Conda, Python 3.10
Hardware: Dell g5 5587, core i7 8th gen, 16 GB RAM, 1050ti 4GB VRAM

It all worked after installing the missing packages.

### CODE REVIEW

**Comment by lintool** [comment]
Hi @AhmedEssam19 what packages are we missing?

**Comment by AhmedEssam19** [comment]
@lintool After installing pyserini in editable mode, it threw errors due to faiss and torch being missing

**Comment by AhmedEssam19** [comment]
@lintool I just noticed that faiss and torch are mentioned in the Pypi installation, not in the development section.

**Comment by lintool** [comment]
Did you follow our installation instructions: https://github.com/castorini/pyserini/blob/master/docs/installation.md

Where it clearly explains how to install faiss, etc.

Under the "Development Installation", it clear says "Start the same way as the install above..."

**Comment by AhmedEssam19** [comment]
@lintool Thanks for the clarification

**Review by lintool — APPROVED** [review]

**Pull request merged**
