### PR TITLE
Refactoring/Upgrade: Exposing topics and other fixes

### PR DESCRIPTION
**Pull request by lintool**
This is the package currently deployed at TestPyPI: https://test.pypi.org/project/pyserini/0.6.1.post0/

The fatjar is based on `0ed488` in Anserini, dated `Sun Nov 17 19:08:26 2019 -0500`.

Working colab notebook at: https://colab.research.google.com/drive/1nY1bjwop3Enygrks-208EilhiCYmYKT6

Still need to update docs, but code itself is ready for CR I think.

I'd also appreciate opinions on publishing SNAPSHOT versions of the fatjar that aren't in Maven... Current package is on TestPyPI, so it really doesn't matter... but any strong opinions on publishing in official PyPI?

The tradeoff is between iteration speed vs. "doing it right". PyPI packages are supposed to be permanent, so depending on a snapshot jar is janky.

### CODE REVIEW

**Comment by zeynepakkalyoncu** [comment]
I think we can hold off on publishing on PyPI for now? We can re-consider later when the Anserini/Pyserini connection is more mature and doesn't require as frequent updates?

**Comment by lintool** [comment]
Okay, and continue to push out interim releases on TestPyPI for those on the real bleeding edge?

**Comment by zeynepakkalyoncu** [comment]
Yes, sounds like a plan!

**Comment by lintool** [comment]
I'll let @emmileaf take a look before merging...

**Comment by emmileaf** [comment]
LGTM!

**Pull request merged**
