### PR TITLE
Add to onboarding reproduction logs

### PR DESCRIPTION
**Pull request by shayanbali**
Everything worked

### CODE REVIEW

**Comment by lintool** [comment]
Please provide more details on setup, etc.
Please continue along the onboarding path until you research the end of the exercises, and then we'll take a look all at once.

**Comment by shayanbali** [comment]
Actually, I use a MacBook Pro M2 to complete these tasks, and I encountered this error during unit testing:

ImportError: dlopen(/Users/shayan/anaconda3/envs/pyserini/lib/python3.8/site-packages/faiss/_swigfaiss.so, 0x0002): Library not loaded: @rpath/libmkl_intel_lp64.1.dylib

**Comment by shayanbali** [comment]
Finally, I found the solution of this problem.
Adding "arch -x86_64" before running could be effective(With rosetta).

**Comment by shayanbali** [comment]
I have successfully resolved the conflicts. Please review the changes.

**Comment by shayanbali** [comment]
Dear Professor Jimmy Lin,

I wanted to inquire if there are any other issues preventing the approval of my pull request.

Thank you for your time and consideration.

> As previously mentioned, I encountered the following error: ImportError: dlopen(/Users/shayan/anaconda3/envs/pyserini/lib/python3.8/site-packages/faiss/_swigfaiss.so, 0x0002): Library not loaded: @rpath/libmkl_intel_lp64.1.dylib
> 
> This occurred during my unittest on a Macbook Pro M2. I attempted the solutions outlined in the Troubleshooting Tips section, but unfortunately, none of them resolved the problem. Eventually, after trying numerous solutions found online, I discovered that using "arch -x86_64" before commands proved to be effective (with Rosetta).
> 
> Regarding the conflicts that occurred, I had committed my changes to add my reproduction log on October 17th. However, since my changes weren't approved, a new reproduction log was added to the repository. This is the root cause of the conflicts.

**Review by lintool — APPROVED** [review]

**Comment by shayanbali** [comment]
Thank you for your consideration.

**Pull request merged**
