### PR TITLE
Reproducing Results for Pyserini

### PR DESCRIPTION
**Pull request by Pie31415**
# Development Environment
- Fresh WSL Ubuntu 20.04.4 on Windows 10
- Python 3.8.13
- Java 11.0.13
- Apache Maven 3.8.6

# Issues

### Anserini build issue
Issue building Anserini resulting from `no cmake found` and `ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory`.

Resolved by
```bash
sudo apt install cmake   
sudo apt update && sudo apt install -y libtinfo5
```

### Pyserini test case test_rocchio failed
Resolved by adding useNegative=True as parameter to pass into java SimpleSearcher object's setRocchio function

# Discrepancy
Pyserini: BM25 Baseline for MS MARCO Document Retrieval has different results than writeup

Downloaded MS MARCO document dataset using alternative mirror
```
wget https://www.dropbox.com/s/w6caao3sfx9nluo/msmarco-docs.trec.gz -P collections/msmarco-doc
```
since 
```
wget https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-docs.trec.gz -P collections/msmarco-doc
```
timed out.

**Differences:**
---

MD5 Checksum for `msmarco-docs.trec.gz` is different:
Mine is: `71e4d3283d6b669cd8ffc595a8b2687d`
Writeup is: `d4863e4f342982b51b9a8fc668b2d0c0`

---
Mine:
```
$ python tools/scripts/msmarco/msmarco_doc_eval.py \
    --judgments tools/topics-and-qrels/qrels.msmarco-doc.dev.txt \
    --run runs/run.msmarco-doc.bm25tuned.txt

#####################
MRR @100: 0.08741475627540689
QueriesRanked: 5193
#####################
```

Writeup:
```
#####################
MRR @100: 0.2770296928568702
QueriesRanked: 5193
#####################
```

---

Mine:
```
$ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.100 -mmap \
   tools/topics-and-qrels/qrels.msmarco-doc.dev.txt runs/run.msmarco-doc.bm25tuned.trec

map                     all     0.0874
recall_100              all     0.1542
```

Writeup:
```
map                   	all	0.2770
recall_100            	all	0.8076
```

### CODE REVIEW

**Comment by lintool** [comment]
hrm... something really went wrong during reviewer... scores very different. not sure what's going on...

@MXueguang you have experience with Windows?

**Comment by MXueguang** [comment]
it's weird `md5sum` are different.
@Pie31415 Could you double check if you get 3,213,835 docs indexed in the indexing step?

**Comment by MXueguang** [comment]
could you check the size of downloaded file? by `wc -c <filename>`
my guess is the download didn't finish completely

**Comment by lintool** [comment]
> Hmm it seems so.
> 
> ```
> $ wc collections/msmarco-doc/msmarco-docs.trec.gz
> 
> 5376486   30335279 1439072256 collections/msmarco-doc/msmarco-docs.trec.gz
> ```

You can't `wc` a compressed file and get meaningful results. You need to do something like `gunzip -c foo.tar.gz | wc`

**Comment by lintool** [comment]
@Pie31415 can you please resolve the conflicts? thanks!

**Comment by Pie31415** [comment]
> @Pie31415 can you please resolve the conflicts? thanks!

resolved!

**Review by lintool — APPROVED** [review]

**Pull request merged**
