### PR TITLE
Fix all of int()-->isdigit() in  "_base.py"

### PR DESCRIPTION
**Pull request by ChuanMeng**
I still found other "int()" operations in the script _base.py. I've fixed all of them.

### CODE REVIEW

**Comment by lintool** [comment]
Haha, would you be willing to write a test case?

**Comment by lintool** [comment]
Here, for example: https://github.com/castorini/pyserini/blob/master/tests/test_load_topics.py

**Comment by ChuanMeng** [comment]
> Here, for example: https://github.com/castorini/pyserini/blob/master/tests/test_load_topics.py

Hi Jimmy,
I already tested the modified script ("_base.py") on the server of my university. My modified version runs without any errors and the topic keys remain unchanged finally (see the following screenshot).
image

Thank you for contributing Pyserini, which is easy to use :-)
I also really hope, in the future, we can finally support the pre-built indexes on some conversational search datasets, such as Trec cast 19, 20, 21, 22, as well as OR-QuAC.

Cheers,
Chuan

**Comment by lintool** [comment]
@ChuanMeng - what I meant was, can you write a test case to go with your code? ;)

**Comment by ChuanMeng** [comment]
I think you can test using the case in the attachment and use the following function.
  
 def test_trec_topicreader(self):
        path = 'test.tsv'
        self.assertTrue(os.path.exists(path))
        topics = search.get_topics_with_reader('io.anserini.search.topicreader.TrecTopicReader', path)
        self.assertEqual(len(topics), 3)

[test.tsv.zip](https://github.com/castorini/pyserini/files/10035779/test.tsv.zip)

Cheers,
Chuan

**Comment by lintool** [comment]
We prefer to adopt software engineering best practices in my group. Can you please add your test case to the PR? Then make sure `python -m unittest` passes?

**Comment by ChuanMeng** [comment]
I'm sorry that I don't have much experience in software engineering. I have no idea of how to use "python -m unittest". I’d like to leave the standard verification to your group.

**Review by lintool — APPROVED** [review]

**Pull request merged**
