### PR TITLE
Improved error message for RM3 expansion doc vector issue

### LINKED ISSUE #695: Better error message when index doesn't store doc vectors to support RM3 expansion
This allows us to use RM3 query expansion.

### PR DESCRIPTION
**Pull request by HAKSOAT**
Fixes #695 

Raises an error when an attempt is made at setting RM3 for indexes without document vectors.

### CODE REVIEW

**Review by lintool — COMMENTED** [review]
Would it be possible to get a test case? We have existing test cases that create stub indexes - you can hook into that?

**Comment by HAKSOAT** [comment]
@lintool I have not used Lucene before, but I made the assumption here that all indexes will have a doc id of 0 (as the first document), is this assumption correct?

Also, I thought of possibly adding a test case here: https://github.com/castorini/pyserini/blob/b71dbc6dca04b214f95cf609390c3294976f8e8b/tests/test_search.py#L192

But:

1. I wasn't so sure if the index loaded in that test suite has vectors (I should actually confirm myself)
2. If it has vectors, how can I possibly delete them before running the test?

**Comment by HAKSOAT** [comment]
> Would it be possible to get a test case? We have existing test cases that create stub indexes - you can hook into that?

Aha. Answers my question already. I'll take a look :-)

**Comment by lintool** [comment]
Take a look at `tests/test_index_reader.py` - it builds an index as part of the test. You can modify it to build two versions - one storing doc vectors, one not...

Thanks!

**Comment by HAKSOAT** [comment]
Added a test. Any improvements in mind?

**Review by lintool — APPROVED** [review]

**Comment by lintool** [comment]
Hi @HAKSOAT I just realized:

> The [setUp()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp) and [tearDown()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown) methods allow you to define instructions that will be executed before and after each test method.

https://docs.python.org/3/library/unittest.html

So your implementation needlessly builds the index multiple times... which actually means that the original test case was poorly designed also...

I think the right approach is this:

> https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass

Would you mind fixing?

**Comment by HAKSOAT** [comment]
True. I'll do that.

**Pull request merged**
