### PR TITLE
add unittest and integration test for encoder

### PR DESCRIPTION
**Pull request by MXueguang**
- unittest trying to make sure encoder output are correct.
- integration test trying to make sure the full pipeline work

### CODE REVIEW

**Comment by lintool** [comment]
`integrations/resources/sample_collection_cacm/cacm.json` is fairly big?

I usually wget otf from here: https://github.com/castorini/anserini-data/tree/master/CACM

Let's not bloat the repo if there are easy alternatives?

**Review by lintool — CHANGES_REQUESTED** [review]
See comment.

**Comment by lintool** [comment]
Ref #704

**Comment by MXueguang** [comment]
2.4M, not that big. but yes, we can use `wget` to download

**Comment by lintool** [comment]
> 2.4M, not that big. but yes, we can use `wget` to download

It's all relative, I suppose ;)

2.4M doesn't fit on one of these, for example: https://en.wikipedia.org/wiki/Floppy_disk

**Comment by MXueguang** [comment]
tested on my ubuntu machine.

**Review by lintool — APPROVED** [review]

**Pull request merged**
