### PR TITLE
Added reproduction logs and fix for nmslib build issue

### PR DESCRIPTION
**Pull request by KenWuqianghao**
System setup:

OS: macOS Sonoma 14.4.1
Memory: 16GB
Chip: Apple M1 Pro
Python Version: 3.10.14
Java Version: 21.0.3
Maven: 3.9.6

Suggestion: I added a fix to building nmslib on M-series ARM chips and attached a link to the most update to github issue discussion.

### CODE REVIEW

**Comment by lintool** [comment]
> Suggestion: I added a fix to building nmslib on M-series ARM chips and attached a link to the most update to github issue discussion.

Can you explain the context for the error? I haven't any issues for a while... and also, recent reproduction efforts seem to have been okay on M processors...

Also, please fix conflicts.

**Comment by KenWuqianghao** [comment]
> nmslib
Basically when I do pip install I get this error message for nmslib

`  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for nmslib
Successfully built lightgbm
Failed to build nmslib
ERROR: Could not build wheels for nmslib, which is required to install pyproject.toml-based projects`

I'm not sure why others haven't had the issue, but the command did help solve the issue for me.

**Comment by lintool** [comment]
> > nmslib
> > Basically when I do pip install I get this error message for nmslib
> 
> ` note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed cleaning build dir for nmslib Successfully built lightgbm Failed to build nmslib ERROR: Could not build wheels for nmslib, which is required to install pyproject.toml-based projects`
> 
> I'm not sure why others haven't had the issue, but the command did help solve the issue for me.

The installation instructions says to use `conda`: https://github.com/castorini/pyserini/blob/master/docs/installation.md

If `conda` still gives you issues, then we should track down.

Otherwise, please remove your `nmslib` "fix". Also fix conflicts?

**Comment by KenWuqianghao** [comment]
> > > nmslib
> > > Basically when I do pip install I get this error message for nmslib
> > 
> > 
> > ` note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed cleaning build dir for nmslib Successfully built lightgbm Failed to build nmslib ERROR: Could not build wheels for nmslib, which is required to install pyproject.toml-based projects`
> > I'm not sure why others haven't had the issue, but the command did help solve the issue for me.
> 
> The installation instructions says to use `conda`: https://github.com/castorini/pyserini/blob/master/docs/installation.md
> 
> If `conda` still gives you issues, then we should track down.
> 
> Otherwise, please remove your `nmslib` "fix". Also fix conflicts?

I did use conda and I ran the installation again just now. This time the installation went smoothly. I'm not sure what happened previously, might be some sort of package corruption idk. I will fix the conflict and remove the fix.

**Pull request closed without merging**
