### PR TITLE
Add unittest for Gar-T5 prebuilt-topics 

### PR DESCRIPTION
**Pull request by ArthurChen189**

### CODE REVIEW

**Comment by ArthurChen189** [comment]
@lintool

**Comment by lintool** [comment]
@ArthurChen189 are you re-opening new PR?

**Comment by ArthurChen189** [comment]
> @ArthurChen189 are you re-opening new PR?

The are 3 diff files. However, changes for the other two are reflected in master. I'm looking into it... Should only have 1 diff file in the pr.

**Review by ronakice — APPROVED** [review]
LGTM!

**Pull request merged**
