### PR TITLE
Add onboarding reproduction logs  for Pyserini: Steps (3-4)

### PR DESCRIPTION
**Pull request by SumonKantiDey**
Adding reproduction logs:
```
 - experiments-msmarco-passage.md
 - conceptual-framework.md
```

Environment:
```Machine:  macOS Big Sur 11.7.8 (Memory: 16 GB 1600 MHz DDR3, Processor: 2.6 GHz Quad-Core Intel Core i7)
Apache Maven: 3.9.4
Java version: 11.0.2
Python: 3.8.17
```
Every result has been successfully reproducible.

### CODE REVIEW

**Review by lintool — APPROVED** [review]

**Review by lintool — CHANGES_REQUESTED** [review]
Can you complete the remainder of the onboarding path, and I'll merge in your additions all at once? Thanks!

**Comment by SumonKantiDey** [comment]
I have found a problem in ```Pyserini: Contriever Baseline for NFCorpus```
I was trying to index the corpus using ```facebook/contriever-msmarco``` encoder by following the below command
```
python -m pyserini.encode \
  input   --corpus collections/nfcorpus/corpus.jsonl \
          --fields title text \
  output  --embeddings indexes/faiss.nfcorpus.contriever-msmacro \
          --to-faiss \
  encoder --encoder facebook/contriever-msmarco \
          --device cpu \
          --pooling mean \
          --fields title text 
```
However, it's currently stuck and hasn't finished even after 6 to 7 hours, despite the initial estimate that the indexing command would only take about 30 minutes.

Is that thing happening because of my ```Machine:  macOS Big Sur 11.7.8 (Memory: 16 GB 1600 MHz DDR3, Processor: 2.6 GHz Quad-Core Intel Core i7)``` somehow? Prof. @lintool

**Comment by lintool** [comment]
Doesn't seem like anyone else has been having issues... can you describe in more detail? How much progress are you making?

**Comment by SumonKantiDey** [comment]
Screenshot 2023-09-12 at 12 40 30 PM
After loading the Pytorch model, it's stacked here. I have tried a couple of times.

**Comment by lintool** [comment]
Please resolve conflicts. Also, see #1637 for your Python encoding issues.

I'm changing to "draft" for now.

**Comment by lintool** [comment]
Having heard no follow up, closing.

**Pull request closed without merging**
