### PR TITLE
Move beir and odqa 2cr into pyserini

### PR DESCRIPTION
**Pull request by jasper-xian**
WIP (still testing), addressing #1438

### CODE REVIEW

**Comment by lintool** [comment]
hi @jasper-xian can we please keep the old odqa scripts? i.e., so we'll have two copies, the original in `scripts/` and the new 2CR. For BEIR we can remove the original in `scripts/`.

Rationale is that we have in our ECIR paper the repro commands for odqa in `scripts/`... so we want to still make sure it works.

**Comment by jasper-xian** [comment]
Sure, we only need to keep `scripts/run_all_odqa.py` and `scripts/generate_odqa_html.py` right? So I can edit them to point to the correct html templates/yaml files?

**Comment by jasper-xian** [comment]
Also, there's a very slight difference to the report generated from this script than as previous for odqa, but this is due to an inconsistency in definitions: `HITS_1K = set(['GarT5-RRF', 'DPR-DKRR', 'DPR-Hybrid'])` in the file to run everything but `HITS_1K = set(['GarT5-RRF', 'DPR-DKRR'])` in the html generation file.

**Comment by lintool** [comment]
Yes, I think so. See: https://link.springer.com/chapter/10.1007/978-3-031-28241-6_10

This is what we have -
Screen Shot 2023-09-18 at 7 21 12 PM

So let's not break that command - although that command can be refactored itself and point to new yaml files, etc. Does that make sense?

**Comment by lintool** [comment]
> Also, there's a very slight difference to the report generated from this script than as previous for odqa, but this is due to an inconsistency in definitions: `HITS_1K = set(['GarT5-RRF', 'DPR-DKRR', 'DPR-Hybrid'])` in the file to run everything but `HITS_1K = set(['GarT5-RRF', 'DPR-DKRR'])` in the html generation file.

@manveertamber @ronakice any comments there? I suppose we should generate everything?

**Comment by jasper-xian** [comment]
Yeah everything is being generated but on the report we have `DPR-Hybrid` getting `--hits 100` but in the run_all we get `--hits 1000`

**Comment by lintool** [comment]
Ah yes, in that case make consistent. Let's go with 1000?

**Comment by jasper-xian** [comment]
@lintool good for review, I've played around with it a bit but didn't test _everything everything_, let me know if you want me to run them all

**Comment by jasper-xian** [comment]
moved the yaml files for odqa back to `pyserini/resources/` fix the merge conflict, will shift them to `pyserini/2cr/` in another PR

**Review by lintool — APPROVED** [review]

**Comment by lintool** [comment]
Hi @jasper-xian I'm fine with merging this. I'll run on my end and we can patch up additional issues as we discover them.

**Comment by lintool** [comment]
And forgot to mention... thanks for all your hard work on this!

**Comment by jasper-xian** [comment]
no problem! yeah happy to merge and tweak later, I'll send in a short PR moving the yaml files afterwards

**Pull request merged**
