### PR TITLE
Updated Replication Log for Pyserini Passage and Doc

### PR DESCRIPTION
**Pull request by ljatca**
Reproduced the pyserini passage and document ranking experiments for the [initial screening exercise](https://github.com/lintool/guide/blob/master/ura.md).

Hardware:
image

Dev Environment:
JAVA 11.0.2, Maven 3.8.4, Python 3.8.8.

I encountered the following error when running `python -m unittest`:
```
(base) jingliu@Jings-MacBook-Pro-14 pyserini % python -m unittest
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000000167ab2d7f, pid=9550, tid=259
#
# JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
# Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [nmslib.cpython-38-darwin.so+0x44d7f]  _GLOBAL__sub_I_nmslib.cc+0x1f
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/jingliu/Desktop/4B/W23_URA/pyserini/hs_err_pid9550.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
zsh: abort      python -m unittest
(base) jingliu@Jings-MacBook-Pro-14 pyserini % 
```
Even though I was unable to run the unit tests, I was still able to reproduce the experiments successfully. I spent a few hours investigating the issue but couldn't find a fix. I noticed this issue was also faced by @jasper-xian as he mentioned in his [PR](https://github.com/castorini/pyserini/pull/1095). We both used Apple M1 chip MacBook Pro so I guess it is a common problem for M1 MacBook?

Update:
I tried Prof. Lin's [recipe](https://github.com/castorini/pyserini/pull/1378#issuecomment-1343815385) and it is able to fix the issue above. I added an installation guide for Apple M1 machines.

### CODE REVIEW

**Comment by lintool** [comment]
hi @ljatca can you try this? https://github.com/castorini/pyserini/issues/938#issuecomment-1272639811

I have an M1 machine and I've managed to get everything working properly. Here's my recipe:

```bash
% conda env list
% conda create -n pyserini-dev python=3.8
% conda activate pyserini-dev

% conda install wget
% conda install -c conda-forge openjdk=11
% conda install -c conda-forge maven
% conda install -c conda-forge lightgbm
% conda install -c conda-forge faiss-cpu
% conda install pytorch torchvision torchaudio -c pytorch
% pip install --no-binary :all: nmslib
% pip install -e .
```

```

**Comment by ljatca** [comment]
> hi @ljatca can you try this? [#938 (comment)](https://github.com/castorini/pyserini/issues/938#issuecomment-1272639811)
> 
> I have an M1 machine and I've managed to get everything working properly. Here's my recipe:
> 
> ```shell
> % conda env list
> % conda create -n pyserini-dev python=3.8
> % conda activate pyserini-dev
> 
> % conda install wget
> % conda install -c conda-forge openjdk=11
> % conda install -c conda-forge maven
> % conda install -c conda-forge lightgbm
> % conda install -c conda-forge faiss-cpu
> % conda install pytorch torchvision torchaudio -c pytorch
> % pip install --no-binary :all: nmslib
> % pip install -e .
> ```

Yeah sure, I tried your recipe and it worked! The unit tests are passing now. I can help with updating the [Development Installation](https://github.com/castorini/pyserini/blob/master/docs/installation.md#development-installation) and add instructions for M1 machines.

**Review by lintool — CHANGES_REQUESTED** [review]
Instead of writing a separate "M1 guide", can you fold the additional instructions to https://github.com/castorini/pyserini/blob/master/docs/installation.md#troubleshooting-tips ?

**Comment by ljatca** [comment]
> Instead of writing a separate "M1 guide", can you fold the additional instructions to https://github.com/castorini/pyserini/blob/master/docs/installation.md#troubleshooting-tips ?

Sure, I removed the separate M1 installation guide and updated the Troubleshooting Tips section

**Review by lintool — APPROVED** [review]

**Pull request merged**
