### PR TITLE
add remove_dups argument for dense retrieval

### PR DESCRIPTION
**Pull request by yogeswarl**
This commit allows duplicate documents to be removed from final dense search results

### CODE REVIEW

**Comment by yogeswarl** [comment]
@lintool is there any update on this pull request. This commit allows removal of duplicate documents in final dense search results. It was available for lucene but missed out in Faiss

**Comment by yogeswarl** [comment]
hi @lintool, Is this change mergeable? It improves dense retrieval results.

**Review by lintool — APPROVED** [review]

**Comment by lintool** [comment]
Sorry for the delay. Merged!

**Comment by lintool** [comment]
ugh. There's a bug:

```
  File "/Users/jimmylin/workspace/pyserini/pyserini/search/faiss/_searcher.py", line 486
    if idx not in unique_docs:
```

@yogeswarl I guess you didn't try running `python -m unittest` did you? :(

**Comment by lintool** [comment]
Hi @yogeswarl Please try again? If you want this feature merged, please send a PR that adds a test case and passes `python -m unittests`?

**Comment by yogeswarl** [comment]
Oh sorry, I will do that and update this pull request.

**Pull request merged**
