### PR TITLE
Add raw() to DenseSearchResult and PRFDenseSearchResult

### LINKED ISSUE #1856: Add convenience method to get raw text from dense retrieval for prebuilt indexes
This issue has come up more than once, the most recent being #1548

Our dense indexes don't store the raw text, but if it's a prebuilt index, we know the corresponding sparse index that has the text. It should be possible to implement a `raw` method that loads the corresponding sparse index to fetch the document.

### PR DESCRIPTION
**Pull request by DanielKohn1208**
closes #1856 by adding a `raw` method to both `DenseSearchResult` and `PRFDenseSearchResult`

Had to change how `DenseSearchResult` and `PRFDenseSearchResult` is initialized as well.

### CODE REVIEW

**Comment by lintool** [comment]
hey @manveertamber can you take a look at this?

**Comment by manveertamber** [comment]
@DanielKohn1208 can you add some documentation to explain how to fetch document content for documents retrieved using a dense index: https://github.com/castorini/pyserini/blob/master/docs/usage-fetch.md. It looks like right now we only explain how to do this for a lucene index

**Comment by manveertamber** [comment]
We can call .doc() on a FaissSearcher too, which routes to the lucene index .doc() but the documentation doesn't explain this either.

**Comment by manveertamber** [comment]
@DanielKohn1208 looks good! But maybe change the headings in the doc to  Using a Lucene Index and Using a Faiss Index instead of Using a Sparse Representation and Using a Dense Representation

**Comment by DanielKohn1208** [comment]
@manveertamber After going through the documentation, I think that I approached this issue in completely the wrong way. As it is now, my fix actually doesn't actually solve any problems. Someone could already get a hit's raw content from a FaissIndex as follows
```python
from pyserini.search.faiss import FaissSearcher, AutoQueryEncoder

DENSE_INDEX = 'beir-v1.0.0-nfcorpus.bge-base-en-v1.5'
encoder = AutoQueryEncoder('BAAI/bge-base-en-v1.5', device='cpu', pooling='mean', l2_norm=True)
searcher = FaissSearcher.from_prebuilt_index(DENSE_INDEX, encoder)
hits = searcher.search('How to Help Prevent Abdominal Aortic Aneurysms')
doc = searcher.doc(hits[0].docid)
raw_content = doc.raw()
```
Also note that my original assumption about the `LuceneSearcher.search()` method returning a list of objects with a `raw()` method was incorrect. Obtaining the raw content of one of these hits would be similar to above code.

Perhaps I am completely misunderstanding the original issue, but I think all that is actually needed is a documentation update?

**Comment by manveertamber** [comment]
Yeah I agree. https://github.com/castorini/pyserini/issues/1548 wanted to get raw text from a DenseSearchResult, but the right way to do this is to just to call searcher.doc(docid), which is possible with a FaissSearcher, we just needed the documentation to reflect this. @lintool is this enough to close https://github.com/castorini/pyserini/issues/1856?

**Comment by DanielKohn1208** [comment]
Should I close this PR and create a new one at some point to update the docs?

**Comment by manveertamber** [comment]
> Should I close this PR and create a new one at some point to update the docs?

Yeah that works.

**Comment by DanielKohn1208** [comment]
Closing PR

**Comment by Xnhyacinth** [comment]
> @manveertamber After going through the documentation, I think that I approached this issue in completely the wrong way. As it is now, my fix actually doesn't actually solve any problems. Someone could already get a hit's raw content from a FaissIndex as follows
> 
> ```python
> from pyserini.search.faiss import FaissSearcher, AutoQueryEncoder
> 
> DENSE_INDEX = 'beir-v1.0.0-nfcorpus.bge-base-en-v1.5'
> encoder = AutoQueryEncoder('BAAI/bge-base-en-v1.5', device='cpu', pooling='mean', l2_norm=True)
> searcher = FaissSearcher.from_prebuilt_index(DENSE_INDEX, encoder)
> hits = searcher.search('How to Help Prevent Abdominal Aortic Aneurysms')
> doc = searcher.doc(hits[0].docid)
> raw_content = doc.raw()
> ```
> 
> Also note that my original assumption about the `LuceneSearcher.search()` method returning a list of objects with a `raw()` method was incorrect. Obtaining the raw content of one of these hits would be similar to above code.
> 
> Perhaps I am completely misunderstanding the original issue, but I think all that is actually needed is a documentation update?


hello. I wonder if this only applies to prebuilt indexes? I encounter an error `AttributeError: 'FaissSearcher' object has no attribute 'ssearcher'. Did you mean: 'search'?`  when using the following code:
```python
from pyserini.search.faiss import FaissSearcher
from pyserini.search.lucene import LuceneSearcher
searcher = FaissSearcher( # dense
    'indexes/index', # file path
    'facebook/contriever-msmarco' # model name
    )
#hits = searcher.search('what is a lobster roll')
searcher.doc(0)
```
I cannot get the raw content through `doc(doc_id)`, but executing `searcher.num_docs` is ok.

**Comment by lintool** [comment]
hi @Xnhyacinth thanks for noting... can you please file a new issue?

**Comment by Xnhyacinth** [comment]
> hi @Xnhyacinth thanks for noting... can you please file a new issue?

sure

**Pull request closed without merging**
