### PR TITLE
Replicated MS MARCO passage/document ranking results with Pyserini

### PR DESCRIPTION
**Pull request by yemiliey**
# Environment
- Google Colab (Python3 Google Compute Engine Backend)
- Python 3.6

**Replicated results are exactly the same as the given results**

# Passage Replication Results

> Given Results

Screenshot from 2021-01-17 04-24-16

>My Results

Screenshot from 2021-01-17 04-24-28

# Document Replication Results
>Given Results

Screenshot from 2021-01-17 03-59-12

>My Results

Screenshot from 2021-01-17 03-58-57

### CODE REVIEW

**Comment by lintool** [comment]
Can you look at https://github.com/castorini/pyserini/pull/341 and compare?

**Comment by lintool** [comment]
This hasn't been merged yet...?

**Comment by yemiliey** [comment]
Ahhhh sorry, I was looking into the issue for #341 and accidentally closed this

**Comment by lintool** [comment]
See #342 - I just wanted an extra pair of eyes to sanity check.

**Comment by yemiliey** [comment]
Ohhh didn't notice that there is already a fix for it, thanks

**Review by lintool — APPROVED** [review]

**Pull request merged**
