### PR TITLE
Updated Wikipedia DPR 100 Word Passage Indices

### PR DESCRIPTION
**Pull request by KaiSun314**

### CODE REVIEW

**Review by MXueguang — APPROVED** [review]
LGTM!

**Comment by lintool** [comment]
@KaiSun314 did we check in the script that converts the raw corpus into something Pyserini can index?

**Comment by MXueguang** [comment]
@lintool should we leave the script in pyserini or put into tools? since it is for anserini

**Comment by lintool** [comment]
Actually, you're right - tools.

**Comment by KaiSun314** [comment]
I created a pull request with the script in anserini-tools: https://github.com/castorini/anserini-tools/pull/28

**Pull request merged**
