### PR TITLE
Add OpenAI text-embedding-3-large msmarco 2cr

### PR DESCRIPTION
**Pull request by manveertamber**

### CODE REVIEW

**Comment by lintool** [comment]
@manveertamber can you please add a README?

**Comment by manveertamber** [comment]
> @manveertamber can you please add a README?

Where would the README go? I'm seeing anything similar for ada2 for example except for in docs/prebuilt-indexes.md

**Comment by lintool** [comment]
README goes in `pyserini/resources/index-metadata`.

>  I'm seeing anything similar for ada2 for example except for in docs/prebuilt-indexes.md

Yea... unfortunately, we haven't been as good about documenting as we should have... but let's change that please.

**Comment by manveertamber** [comment]
> README goes in `pyserini/resources/index-metadata`.
> 
> > I'm seeing anything similar for ada2 for example except for in docs/prebuilt-indexes.md
> 
> Yea... unfortunately, we haven't been as good about documenting as we should have... but let's change that please.

Sounds good

**Review by lintool — APPROVED** [review]

**Pull request merged**
