### PR TITLE
Add DPR demo

### LINKED ISSUE #633: Demo for DPR?
The MS MARCO demo is nice... @saileshnankani can we get a dpr demo also?

### PR DESCRIPTION
**Pull request by saileshnankani**
This PR adds a demo for DPR, similar to [MSMarcoDemo](https://github.com/castorini/pyserini/blob/master/pyserini/demo/msmarco.py). Currently, it only supports `DPR-Multi` and `/random` chooses topics from  [`Natural Questions`](https://github.com/castorini/pyserini/blob/master/pyserini/search/_base.py#L198) and [`Trivia`](https://github.com/castorini/pyserini/blob/master/pyserini/search/_base.py#L202) collections.

Resolves #633

### CODE REVIEW

**Review by MXueguang — APPROVED** [review]
lgtm

**Comment by ronakice** [comment]
@MXueguang this won't be runnable in a colab right?

**Comment by MXueguang** [comment]
> @MXueguang this won't be runnable in a colab right?

no. the index is in original size for the demo right now.
we can support compression index for demo later. e.g. with pq.

**Comment by lintool** [comment]
@MXueguang I'll let you merge in when ready?

**Pull request merged**
