### PR TITLE
Add to onboarding doc with updated scores

### PR DESCRIPTION
**Pull request by Lindaaa8**

### CODE REVIEW

**Comment by lintool** [comment]
Can you describe your setup? OS, versions, etc.?

Odd that you're finding slight differences...

**Comment by lintool** [comment]
Hi @Lindaaa8 let's not change the effectiveness numbers... might be due to your idiosyncratic setup because others haven't noticed... if we hear more from others we can circle back to tweak?

So please revert those changes?

**Comment by lintool** [comment]
I think you're missing the final step in the in onboarding path?

**Comment by Lindaaa8** [comment]
Added the missing final step.

**Review by lintool — APPROVED** [review]

**Pull request merged**
